version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - caching-network

 

networks:
  caching-network:
    driver: bridge
